const CWS = [
  { id:1, title:"Kreativ pedagogika fan sifatida", sub:"Ijod – bilimni amaliyotga aylantiruvchi kuch!",
    words:[
      {n:1, w:'KREATIVLIK', r:11, c:9, d:'H', q:"Yangi va original g'oyalarni yaratish qobiliyati."},
      {n:20, w:'POTENSIAL', r:9, c:13, d:'V', q:"Shaxsning rivojlanish imkoniyati."},
      {n:19, w:'PEDAGOG', r:10, c:11, d:'V', q:"O'quvchi faoliyatini boshqaruvchi shaxs."},
      {n:18, w:'KREATIVTAFAKKUR', r:11, c:9, d:'V', q:"Yangilik yaratishga yo'naltirilgan fikrlash turi."},
      {n:17, w:'MUTAXASSISLIK', r:8, c:12, d:'V', q:"Kasb egasining faoliyat sohasi."},
      {n:16, w:'TALIM', r:9, c:16, d:'V', q:"Bilimlarni egallash jarayoni."},
      {n:15, w:'MAHORAT', r:7, c:10, d:'V', q:"O'qituvchining kasbiy faoliyati natijasi."},
      {n:14, w:'YETUKLIK', r:7, c:18, d:'V', q:"Mutaxassisning kasbiy rivojlanish bosqichi."},
      {n:13, w:'GLOBALLASHUV', r:0, c:15, d:'V', q:"Dunyo miqyosidagi integratsiya jarayoni."},
      {n:12, w:'METODOLOGIYA', r:2, c:14, d:'V', q:"Ilmiy izlanish usullarini o'rganuvchi soha."},
      {n:11, w:'IJODKORLIK', r:11, c:17, d:'V', q:"Kreativ pedagogika o'rganadigan asosiy sifat."},
      {n:10, w:'KOMPETENSIYA', r:22, c:9, d:'H', q:"Bilimlarni amalda qo'llash qobiliyati."},
      {n:9, w:'NAZARIYA', r:21, c:8, d:'H', q:"Nazariy qarashlar tizimi."},
      {n:8, w:'KASBIYLIK', r:23, c:9, d:'H', q:"Kasbga oid faoliyat."},
      {n:7, w:'TAFAKKUR', r:20, c:7, d:'H', q:"Fikr yuritish jarayoni."},
      {n:6, w:'METOD', r:8, c:17, d:'H', q:"Muayyan faoliyatni bajarish usuli."},
      {n:5, w:'INNOVATSIYA', r:19, c:4, d:'H', q:"Yangilik yaratish va joriy etish jarayoni."},
      {n:4, w:'SALOHIYAT', r:15, c:1, d:'H', q:"Shaxsning ichki imkoniyatlari majmui."},
      {n:3, w:'TADQIQOT', r:4, c:14, d:'H', q:"Ilmiy izlanish olib borish jarayoni."},
      {n:2, w:'PEDAGOGIKA', r:14, c:0, d:'H', q:"Ta'lim va tarbiya haqidagi fan."}
    ]},

  { id:2, title:"Kreativ ta'lim muhiti", sub:"Bilim – tafakkurda, ijod – yondashuvda!",
    words:[
      {n:1, w:'MUHIT', r:6, c:10, d:'H', q:"Insonni o'rab turgan sharoitlar majmui."},
      {n:20, w:'FAOLLIK', r:1, c:13, d:'V', q:"O'quv faoliyatini rag'batlantirish vositasi."},
      {n:19, w:'MUSTAQILLIK', r:6, c:10, d:'V', q:"Mustaqil fikr yuritish qobiliyati."},
      {n:18, w:'MOTIVATSIYA', r:4, c:14, d:'V', q:"O'quvchining ichki qiziqishi."},
      {n:17, w:'KASHFIYOT', r:3, c:12, d:'V', q:"Yangi bilim yaratish faoliyati."},
      {n:13, w:'BERUNIY', r:3, c:11, d:'V', q:"Qomusiy olim."},
      {n:10, w:'KLASTER', r:2, c:11, d:'H', q:"Fikrlar xaritasi usuli."},
      {n:9, w:'SHAROIT', r:10, c:8, d:'H', q:"O'quv jarayonini tashkil etuvchi omil."},
      {n:8, w:'EVRISTIKA', r:15, c:7, d:'H', q:"Muammoni hal qilishning samarali usuli."},
      {n:7, w:'IJODKORLIK', r:16, c:6, d:'H', q:"Yangi g'oya yaratish qobiliyati."},
      {n:6, w:'BILIM', r:13, c:8, d:'H', q:"O'quvchi faoliyatining asosiy natijasi."},
      {n:5, w:'DAVRIYLIK', r:14, c:4, d:'H', q:"Muayyan davrlar bo'yicha rivojlanish."},
      {n:4, w:'TABAQALANISH', r:12, c:1, d:'H', q:"Guruhlarga ajratish jarayoni."},
      {n:3, w:'KREATIVMUHIT', r:6, c:3, d:'H', q:"Ijodiy faoliyatga undovchi muhit turi."},
      {n:16, w:'IZLANISH', r:9, c:2, d:'V', q:"Yangilik izlashga asoslangan usul."},
      {n:15, w:'TRANSFORMATSIYA', r:2, c:1, d:'V', q:"Bilimlarni yangi vaziyatda qo'llash darajasi."},
      {n:14, w:'IBNSINO', r:2, c:8, d:'V', q:"Tib qonunlari asari muallifi."},
      {n:12, w:'FARGONIY', r:0, c:17, d:'V', q:"Buyuk astronom olim."},
      {n:11, w:'XORAZMIY', r:3, c:6, d:'V', q:"Algebra fanining asoschilaridan biri."},
      {n:2, w:'TALIM', r:11, c:0, d:'H', q:"Bilim berish jarayoni."}
    ]},

  { id:3, title:"Didaktik ta'minotni yaratishga kreativ yondashuv", sub:"Kreativ yondashuv – ta'limning yuragi!",
    words:[
      {n:1, w:'DIDAKTIKA', r:5, c:4, d:'H', q:"Ta'lim nazariyasi va amaliyoti fani."},
      {n:20, w:'INNOVATSIYA', r:5, c:5, d:'V', q:"Pedagogik yangilik."},
      {n:19, w:'MASHGULOT', r:4, c:7, d:'V', q:"O'quv faoliyatining shakli."},
      {n:18, w:'STANDART', r:4, c:9, d:'V', q:"O'quv maqsadini belgilovchi hujjat."},
      {n:17, w:'SAMARADORLIK', r:4, c:12, d:'V', q:"O'qituvchi faoliyatining natijasi."},
      {n:16, w:'TOPSHIRIQ', r:0, c:10, d:'V', q:"O'quvchiga beriladigan vazifa."},
      {n:13, w:'YONDASHUV', r:2, c:4, d:'V', q:"Yangi usul bilan ishlash jarayoni."},
      {n:10, w:'RESURS', r:12, c:0, d:'H', q:"O'quv faoliyatini tashkil etuvchi vosita."},
      {n:9, w:'MUALLIFLIKDASTURI', r:15, c:3, d:'H', q:"Pedagogning ijodiy mahsuli."},
      {n:8, w:'TOPLASH', r:11, c:11, d:'H', q:"Axborotlarni yig'ish jarayoni."},
      {n:7, w:'FAN', r:6, c:3, d:'H', q:"O'quv rejasining tarkibiy qismi."},
      {n:6, w:'SARALASH', r:4, c:12, d:'H', q:"O'quv materiallarini tanlash jarayoni."},
      {n:5, w:'QOLLANMA', r:13, c:10, d:'H', q:"O'quvchiga yordam beruvchi adabiyot."},
      {n:4, w:'DARSLIK', r:13, c:0, d:'H', q:"Asosiy o'quv manbasi."},
      {n:3, w:'DTS', r:10, c:12, d:'H', q:"Davlat ta'lim standartining qisqartmasi."},
      {n:2, w:'DASTUR', r:9, c:11, d:'H', q:"O'quv jarayonini tartibga soluvchi hujjat."},
      {n:15, w:'NAZORAT', r:3, c:17, d:'V', q:"Bilimlarni baholash vositasi."},
      {n:14, w:'MAVZU', r:3, c:13, d:'V', q:"O'quv materialining mazmuniy qismi."},
      {n:12, w:'AXBOROT', r:0, c:14, d:'V', q:"Ma'lumotlar majmui."},
      {n:11, w:'OQUVREJA', r:11, c:18, d:'V', q:"O'quv jarayonini rejalashtirish hujjati."}
    ]},

  { id:4, title:"Bo'lajak o'qituvchilarda kreativ tasavvur va ilmiy ijodkorlik", sub:"Ijodkor o'qituvchi – zamonaviy ta'lim poydevori!",
    words:[
      {n:1, w:'TASAVVUR', r:6, c:5, d:'H', q:"Ongda yangi obrazlar yaratish qobiliyati."},
      {n:20, w:'MAQOLA', r:5, c:6, d:'V', q:"Ilmiy faoliyat mahsuli."},
      {n:18, w:'METOD', r:4, c:5, d:'V', q:"Muammo yechishga qaratilgan usul."},
      {n:17, w:'SALOHIYAT', r:6, c:7, d:'V', q:"Bilim va tajriba majmui."},
      {n:16, w:'ORIGINALLIK', r:5, c:12, d:'V', q:"O'ziga xos yondashuv."},
      {n:15, w:'FANTAZIYA', r:5, c:8, d:'V', q:"Tasavvurga asoslangan fikrlash turi."},
      {n:14, w:'TAFAKKUR', r:0, c:11, d:'V', q:"Fikr yuritish qobiliyati."},
      {n:10, w:'GOYA', r:8, c:12, d:'H', q:"Ijodiy fikr mahsuli."},
      {n:9, w:'KOMPETENTLIK', r:14, c:2, d:'H', q:"Bilimlarni amalda qo'llash qobiliyati."},
      {n:8, w:'INNOVATSIYA', r:9, c:12, d:'H', q:"Yangilik joriy qilish faoliyati."},
      {n:7, w:'MUTAXASSIS', r:0, c:9, d:'H', q:"Kasbiy tayyorgarlikka ega shaxs."},
      {n:6, w:'TADQIQOTCHI', r:11, c:11, d:'H', q:"Ilmiy izlanish olib boruvchi shaxs."},
      {n:5, w:'YECHIM', r:4, c:0, d:'H', q:"Muammoni hal qilishning yakuniy natijasi."},
      {n:4, w:'KREATIVLIK', r:15, c:12, d:'H', q:"Yangilik yaratishga oid sifat."},
      {n:2, w:'ILMIYIJOD', r:12, c:11, d:'H', q:"Yangi ilmiy g'oyalar yaratish faoliyati."},
      {n:19, w:'BILIM', r:3, c:4, d:'V', q:"O'quvchi faoliyatining natijasi."},
      {n:13, w:'KASHFIYOT', r:7, c:3, d:'V', q:"Yangi bilim yaratish jarayoni."},
      {n:12, w:'TEXNOLOGIYA', r:3, c:1, d:'V', q:"O'qitishning zamonaviy vositasi."},
      {n:11, w:'TADQIQOT', r:8, c:22, d:'V', q:"Muammoni hal qilishga qaratilgan faoliyat."},
      {n:3, w:'IXTIRO', r:15, c:1, d:'H', q:"Yangi qurilma yoki usul yaratish jarayoni."}
    ]},

  { id:5, title:"Kreativ kompetensiya modelining shakllanishi", sub:"Bilim, ijod, mahorat – muvaffaqiyat kaliti!",
    words:[
      {n:1, w:'KOMPETENSIYA', r:6, c:9, d:'H', q:"Bilim va ko'nikmalar majmui."},
      {n:20, w:'OZRIVOJLANTIRISH', r:6, c:10, d:'V', q:"O'z ustida ishlash faoliyati."},
      {n:19, w:'TALIM', r:6, c:14, d:'V', q:"Bilimlarni egallash jarayoni."},
      {n:18, w:'INDIVIDUALLIK', r:6, c:18, d:'V', q:"Shaxsning individual uslubi."},
      {n:17, w:'YETUKLIK', r:6, c:19, d:'V', q:"Kasbiy rivojlanish bosqichi."},
      {n:16, w:'MULOQOT', r:6, c:11, d:'V', q:"O'quvchilar bilan aloqa o'rnatish qobiliyati."},
      {n:15, w:'ETIKA', r:6, c:13, d:'V', q:"Pedagogik madaniyatning tarkibiy qismi."},
      {n:14, w:'TAYYORGARLIK', r:5, c:20, d:'V', q:"Kasbiy bilimlar yig'indisi."},
      {n:13, w:'FAOLLIK', r:0, c:9, d:'V', q:"Ijodiy tashabbus ko'rsatish holati."},
      {n:10, w:'INSONPARVARLIK', r:19, c:10, d:'H', q:"Inson manfaatlarini ustun qo'yuvchi yondashuv."},
      {n:9, w:'FAOLIYAT', r:14, c:17, d:'H', q:"Maqsadli harakatlar tizimi."},
      {n:8, w:'GNOSTIK', r:15, c:9, d:'H', q:"Bilish faoliyatiga oid qobiliyat."},
      {n:7, w:'PROFESSIOGRAMMA', r:20, c:5, d:'H', q:"O'qituvchi faoliyatiga qo'yilgan talablar tavsifi."},
      {n:6, w:'MALAKA', r:16, c:16, d:'H', q:"Kasbiy tayyorgarlik darajasi."},
      {n:5, w:'KOMMUNIKATIVLIK', r:17, c:0, d:'H', q:"Muloqotga kirishish qobiliyati."},
      {n:4, w:'IJODKORLIK', r:18, c:4, d:'H', q:"Yangi g'oyalar yaratish qobiliyati."},
      {n:3, w:'MADANIYAT', r:14, c:7, d:'H', q:"Jamiyat taraqqiyotini ifodalovchi qadriyatlar tizimi."},
      {n:2, w:'MODEL', r:13, c:6, d:'H', q:"Namuna yoki andoza."},
      {n:12, w:'OQITUVCHI', r:6, c:21, d:'V', q:"O'quv jarayonini tashkil etuvchi shaxs."},
      {n:11, w:'MAHORAT', r:8, c:24, d:'V', q:"Pedagogning kasbiy ustaligi."}
    ]},

  { id:6, title:"O'qituvchining ta'lim jarayoniga kreativ yondashuvi", sub:"Ijodkor o'qituvchi – zamonaviy ta'lim poydevori!",
    words:[
      {n:1, w:'INNOVATSIYA', r:10, c:7, d:'H', q:"Yangilik joriy qilish jarayoni."},
      {n:20, w:'SAMARADORLIK', r:10, c:14, d:'V', q:"Ta'lim sifati ko'rsatkichi."},
      {n:19, w:'PLATFORMA', r:8, c:12, d:'V', q:"Zamonaviy pedagogik vosita."},
      {n:18, w:'RAGBATLANTIRISH', r:9, c:17, d:'V', q:"Mustaqil fikrlashga undash."},
      {n:17, w:'REJALASHTIRISH', r:2, c:13, d:'V', q:"O'quv maqsadini aniqlash."},
      {n:16, w:'MALAKAOSHIRISH', r:4, c:10, d:'V', q:"Kasbiy mahoratni rivojlantirish."},
      {n:15, w:'TASHKILOT', r:5, c:7, d:'V', q:"O'quv faoliyatini boshqarish."},
      {n:14, w:'RAQAMLASHTIRISH', r:0, c:15, d:'V', q:"Axborot texnologiyalaridan foydalanish."},
      {n:11, w:'NATIJA', r:10, c:8, d:'V', q:"Pedagog faoliyatining samaradorligi."},
      {n:10, w:'DARS', r:7, c:12, d:'H', q:"Ta'limning asosiy shakli."},
      {n:9, w:'TEXNOLOGIYA', r:19, c:9, d:'H', q:"Darsni tashkil etish usullari majmui."},
      {n:8, w:'LABORATORIYA', r:15, c:17, d:'H', q:"Tajriba asosida o'qitish shakli."},
      {n:7, w:'SEMINAR', r:20, c:11, d:'H', q:"Muhokamaga asoslangan mashg'ulot turi."},
      {n:6, w:'MAHORAT', r:16, c:16, d:'H', q:"Pedagogning kasbiy ustaligi."},
      {n:5, w:'KOOPERATSIYA', r:3, c:9, d:'H', q:"Hamkorlikda ishlash jarayoni."},
      {n:4, w:'TADQIQOT', r:12, c:1, d:'H', q:"Ilmiy izlanish faoliyati."},
      {n:3, w:'MOTIVATSIYA', r:7, c:0, d:'H', q:"Faoliyatga undovchi ichki omil."},
      {n:2, w:'INTERAKTIVLIK', r:18, c:10, d:'H', q:"Faol muloqotga asoslangan ta'lim."},
      {n:13, w:'FAOLLASHTIRISH', r:10, c:28, d:'V', q:"O'quvchini faoliyatga jalb qilish."},
      {n:12, w:'OQITISH', r:10, c:5, d:'V', q:"Bilim berish jarayoni."}
    ]},

  { id:7, title:"Kreativ topshiriqlar tizimi", sub:"Kalit so'z: KREATIVPEDAGOGIKA",
    words:[
      {n:1, w:'MOTIVLASHTIRISH', r:3, c:5, d:'H', q:"O'quvchini faoliyatga undash jarayoni."},
      {n:20, w:'TAKRORLASH', r:3, c:7, d:'V', q:"Bilimlarni mustahkamlash bosqichi."},
      {n:19, w:'LOYIHA', r:3, c:10, d:'V', q:"O'quv faoliyatining turi."},
      {n:18, w:'KEYS', r:0, c:12, d:'V', q:"Muammoni yechishga qaratilgan topshiriq."},
      {n:17, w:'MONITORING', r:3, c:5, d:'V', q:"O'quvchi faoliyatini baholash."},
      {n:16, w:'KOMPETENSIYA', r:2, c:6, d:'V', q:"Darsning maqsadli natijasi."},
      {n:15, w:'MUHOKAMA', r:1, c:13, d:'V', q:"Fikrlar almashinuvi jarayoni."},
      {n:14, w:'IJODKORLIK', r:3, c:8, d:'V', q:"Yangi g'oyalarni yaratish faoliyati."},
      {n:13, w:'IZLANISH', r:3, c:15, d:'V', q:"Muammoli vaziyatni hal qilish."},
      {n:12, w:'MOTIVATOR', r:1, c:14, d:'V', q:"O'quvchini hayratga soluvchi usul."},
      {n:11, w:'TOPSHIRIQ', r:0, c:18, d:'V', q:"Kreativ darsning asosiy elementi."},
      {n:10, w:'YECHIM', r:10, c:12, d:'H', q:"Masalani hal qilish jarayoni."},
      {n:9, w:'INDIVIDUALLIK', r:0, c:0, d:'H', q:"O'quvchining o'ziga xosligi."},
      {n:8, w:'DIAGNOSTIKA', r:13, c:4, d:'H', q:"Muammoni aniqlash jarayoni."},
      {n:7, w:'FANTAZIYA', r:0, c:15, d:'H', q:"Tasavvur mahsuli."},
      {n:6, w:'REFLEKSIYA', r:2, c:1, d:'H', q:"O'z faoliyatini baholash."},
      {n:5, w:'DIZAYN', r:5, c:17, d:'H', q:"Tasviriy loyihalash san'ati."},
      {n:4, w:'KOLABORATSIYA', r:1, c:17, d:'H', q:"Jamoaviy hamkorlik faoliyati."},
      {n:2, w:'SURPRIZ', r:15, c:5, d:'H', q:"Kutilmagan qiziqarli holat."},
      {n:3, w:'ANALIZ', r:17, c:5, d:'H', q:"Tahlil qilish jarayoni."}
    ]},

  { id:8, title:"Pedagogik qobiliyatni shakllantirishda kreativ yondashuv", sub:"Ijod – bilimni amaliyotga aylantiruvchi kuch!",
    words:[
      {n:1, w:'QOBILIYAT', r:7, c:6, d:'H', q:"Faoliyatni muvaffaqiyatli bajarish imkoniyati."},
      {n:20, w:'SAMARADORLIK', r:6, c:13, d:'V', q:"Pedagogik faoliyat natijasi."},
      {n:19, w:'KREATIVFIKRLASH', r:3, c:14, d:'V', q:"Yangi g'oyalarni ishlab chiqish jarayoni."},
      {n:18, w:'FAOLLASHTIRISH', r:5, c:7, d:'V', q:"O'quvchini rag'batlantirish usuli."},
      {n:17, w:'OQITISH', r:6, c:6, d:'V', q:"Bilim berish faoliyati."},
      {n:16, w:'OZUSTIDAISLASH', r:2, c:9, d:'V', q:"Pedagogning shaxsiy rivojlanishi."},
      {n:15, w:'TEXNOLOGIYA', r:2, c:10, d:'V', q:"Zamonaviy o'qitish usullari tizimi."},
      {n:14, w:'HAMKORLIK', r:0, c:11, d:'V', q:"Birgalikda faoliyat yuritish."},
      {n:13, w:'LOYIHA', r:5, c:12, d:'V', q:"Mustaqil amaliy ish shakli."},
      {n:10, w:'MAHORAT', r:18, c:5, d:'H', q:"O'qituvchining kasbiy ustaligi."},
      {n:9, w:'METODIKA', r:16, c:2, d:'H', q:"Kasbiy faoliyatni tashkil etish usuli."},
      {n:8, w:'MALAKA', r:15, c:11, d:'H', q:"Bilimlarni amalda qo'llash qobiliyati."},
      {n:7, w:'INTERAKTIVLIK', r:1, c:6, d:'H', q:"O'qitishning zamonaviy usuli."},
      {n:6, w:'MOTIVATSIYA', r:17, c:0, d:'H', q:"O'quvchini ruhlantirish jarayoni."},
      {n:3, w:'RIVOJLANTIRISH', r:4, c:14, d:'H', q:"Takomillashtirish jarayoni."},
      {n:12, w:'SEMINAR', r:10, c:16, d:'V', q:"Muhokamaga asoslangan dars turi."},
      {n:11, w:'TRENING', r:4, c:22, d:'V', q:"Malaka oshirish mashg'uloti."},
      {n:5, w:'PEDAGOG', r:6, c:21, d:'H', q:"Ta'lim beruvchi mutaxassis."},
      {n:4, w:'INNOVATSIYA', r:13, c:16, d:'H', q:"Yangilik yaratish faoliyati."},
      {n:2, w:'IJODKORLIK', r:8, c:22, d:'H', q:"Yangi g'oyalar yaratish sifati."}
    ]},

  { id:9, title:"Kasbiy kompetensiyalarni shakllantirishda kreativ yondashuv", sub:"Kreativ ta'lim – kelajak poydevori!",
    words:[
      {n:1, w:'KOMPETENTLIK', r:10, c:3, d:'H', q:"Bilim va tajribani amalda qo'llash qobiliyati."},
      {n:20, w:'MONITORING', r:10, c:5, d:'V', q:"Bilimlarni baholash mezoni."},
      {n:19, w:'PEDAGOG', r:10, c:6, d:'V', q:"O'quv faoliyatini tashkil etuvchi shaxs."},
      {n:18, w:'MUSTAQILLIK', r:7, c:8, d:'V', q:"Qaror qabul qilish qobiliyati."},
      {n:17, w:'MALAKAOSHIRISH', r:8, c:12, d:'V', q:"Kasbiy bilimlarni boyitish jarayoni."},
      {n:16, w:'MOSLASHUVCHANLIK', r:9, c:4, d:'V', q:"O'zgaruvchan sharoitga moslashish qobiliyati."},
      {n:15, w:'NATIJA', r:10, c:10, d:'V', q:"Faoliyat samaradorligini belgilovchi omil."},
      {n:14, w:'ETIKA', r:10, c:7, d:'V', q:"Kasbiy odob normalari."},
      {n:13, w:'RAHBARLIK', r:3, c:13, d:'V', q:"Boshqaruv qobiliyati."},
      {n:12, w:'MASULIYAT', r:2, c:11, d:'V', q:"Javobgarlik hissi."},
      {n:11, w:'SAVODXONLIK', r:0, c:3, d:'V', q:"Bilimlilik darajasi."},
      {n:10, w:'HAMKORLIK', r:16, c:12, d:'H', q:"Jamoa bilan ishlash qobiliyati."},
      {n:9, w:'LAYOQAT', r:22, c:4, d:'H', q:"Kasbiy vazifalarni bajarish qobiliyati."},
      {n:8, w:'RIVOJLANISH', r:18, c:12, d:'H', q:"O'z ustida ishlash jarayoni."},
      {n:7, w:'ETIKA', r:17, c:10, d:'H', q:"Pedagogning huquqiy va axloqiy madaniyati."},
      {n:6, w:'KASBIYLIK', r:12, c:12, d:'H', q:"Kasbga oid bilimlar majmui."},
      {n:5, w:'SIFAT', r:7, c:10, d:'H', q:"Shaxsga xos ijobiy xususiyat."},
      {n:4, w:'BILIM', r:9, c:0, d:'H', q:"O'zlashtirilgan ma'lumotlar majmui."},
      {n:3, w:'TAJRIBA', r:3, c:10, d:'H', q:"Faoliyat davomida orttirilgan bilimlar."},
      {n:2, w:'MALAKA', r:20, c:3, d:'H', q:"Kasbiy tayyorgarlik darajasi."}
    ]},

  { id:10, title:"Kreativ kompetensiyaning mazmuni va tuzilishi", sub:"Kreativ yondashuv – zamonaviy ta'limning yuragi!",
    words:[
      {n:1, w:'ERUDITSIYA', r:4, c:9, d:'H', q:"Keng bilim va dunyoqarashga ega bo'lish."},
      {n:20, w:'TUSHUNCHA', r:4, c:14, d:'V', q:"Bilimlarni chuqur o'zlashtirish darajasi."},
      {n:19, w:'KREATIVLIK', r:3, c:10, d:'V', q:"Innovatsion fikrlash jarayoni."},
      {n:18, w:'GOYA', r:2, c:17, d:'V', q:"Kreativ faoliyat mahsuli."},
      {n:17, w:'YECHIM', r:3, c:9, d:'V', q:"Muammolarni hal etish usuli."},
      {n:16, w:'AMALIYOT', r:4, c:18, d:'V', q:"Bilimlarni qo'llash qobiliyati."},
      {n:15, w:'INTERAKTIV', r:4, c:13, d:'V', q:"Faol ishtirokka asoslangan ta'lim."},
      {n:14, w:'TANQIDIYFIKRLASH', r:0, c:16, d:'V', q:"Tanqidiy baholash qobiliyati."},
      {n:13, w:'MULOQOT', r:3, c:11, d:'V', q:"O'zaro fikr almashish."},
      {n:10, w:'TAFAKKUR', r:11, c:18, d:'H', q:"Muammoni tahlil qilish usuli."},
      {n:9, w:'KOMPETENSIYA', r:0, c:11, d:'H', q:"O'quv faoliyatining natijasi."},
      {n:8, w:'IJODKORLIK', r:11, c:2, d:'H', q:"Yangi g'oyalarni yaratish faoliyati."},
      {n:7, w:'ORIGINALLIK', r:12, c:0, d:'H', q:"Muammoga noodatiy yondashish."},
      {n:6, w:'ANALITIKA', r:6, c:18, d:'H', q:"Bilimlar orasidagi bog'liqlikni topish qobiliyati."},
      {n:4, w:'JARAYON', r:1, c:15, d:'H', q:"Muayyan faoliyatning davom etishi."},
      {n:3, w:'KOGNITIV', r:13, c:6, d:'H', q:"Bilish jarayonlariga oid tushuncha."},
      {n:2, w:'SALOHIYAT', r:14, c:16, d:'H', q:"Ichki imkoniyatlar majmui."},
      {n:12, w:'ANALOGIYA', r:3, c:21, d:'V', q:"O'xshashlik asosida fikrlash usuli."},
      {n:11, w:'TAFAKKUR', r:5, c:1, d:'V', q:"Fikr yuritish qobiliyati."},
      {n:5, w:'MEZON', r:17, c:9, d:'H', q:"Baholash mezoni."}
    ]},

  { id:11, title:"Ma'naviy kompetensiyalarni shakllantirishda kreativ yondashuv", sub:"Ma'naviy kompetensiyalarni rivojlantirish yo'lida",
    words:[
      {n:1, w:'MANAVIYAT', r:6, c:11, d:'H', q:"Ruhiy va axloqiy qadriyatlar majmui."},
      {n:20, w:'QADRIYATLAR', r:5, c:12, d:'V', q:"Shaxs rivojlanishining muhim omili."},
      {n:18, w:'TARBIYALASH', r:6, c:19, d:'V', q:"Ijobiy his-tuyg'ularni rivojlantirish jarayoni."},
      {n:17, w:'MULOQOT', r:6, c:11, d:'V', q:"O'quvchi va o'qituvchi o'rtasidagi aloqa."},
      {n:16, w:'MANAVIYAT', r:5, c:14, d:'V', q:"Shaxsning ichki dunyosi bilan bog'liq tushuncha."},
      {n:15, w:'MUAMMO', r:4, c:18, d:'V', q:"Yechim talab qiluvchi vaziyat."},
      {n:14, w:'TANQIDIYFIKRLASH', r:4, c:13, d:'V', q:"Tahliliy fikrlash turi."},
      {n:13, w:'MUSTAQILLIK', r:0, c:16, d:'V', q:"O'z kuchiga tayangan holda ish yuritish."},
      {n:11, w:'EMPATIYA', r:0, c:17, d:'V', q:"Boshqalarning his-tuyg'ularini tushunish."},
      {n:10, w:'OZLIKNIANGLASH', r:13, c:17, d:'H', q:"O'zini anglash jarayoni."},
      {n:9, w:'MUAMMOYECHISH', r:12, c:17, d:'H', q:"Muammolarni hal qilish qobiliyati."},
      {n:8, w:'MOTIVATSIYA', r:17, c:8, d:'H', q:"O'quvchini faollikka undash usuli."},
      {n:7, w:'MUSTAQILLIK', r:3, c:13, d:'H', q:"Mustaqil qaror qabul qilish qobiliyati."},
      {n:6, w:'OZINIIFODAETISH', r:18, c:0, d:'H', q:"O'z fikrini erkin bayon qilish qobiliyati."},
      {n:5, w:'QADRIYAT', r:14, c:18, d:'H', q:"Jamiyat e'tirof etgan qadriyat."},
      {n:4, w:'INTELLEKT', r:10, c:19, d:'H', q:"Aqliy salohiyat darajasi."},
      {n:3, w:'EMOTSIONAL', r:15, c:15, d:'H', q:"Hissiyotlarga oid tushuncha."},
      {n:2, w:'KREATIVLIK', r:16, c:6, d:'H', q:"Yangilik yaratish qobiliyati."},
      {n:19, w:'ODOB', r:16, c:0, d:'V', q:"Axloqiy me'yorlarga amal qilish holati."},
      {n:12, w:'FAOLLIK', r:4, c:26, d:'V', q:"Faollik ko'rsatish holati."}
    ]},

  { id:12, title:"O'qituvchining kreativ salohiyatini rivojlantirish usullari", sub:"Kreativ fikr – yangi kelajakning boshlanishidir!",
    words:[
      {n:1, w:'SALOHIYAT', r:10, c:10, d:'H', q:"Shaxsning ichki imkoniyatlari majmui."},
      {n:20, w:'TAJRIBA', r:10, c:18, d:'V', q:"Kasbiy muvaffaqiyat omili."},
      {n:19, w:'YANGILIK', r:10, c:16, d:'V', q:"O'qituvchining innovatsion faoliyati natijasi."},
      {n:18, w:'ILMIYIJOD', r:10, c:15, d:'V', q:"Bilimlarni yaratish va qo'llash faoliyati."},
      {n:17, w:'ANALIZ', r:10, c:11, d:'V', q:"Muammoni o'rganish usuli."},
      {n:16, w:'TEXNOLOGIYA', r:6, c:13, d:'V', q:"O'quv jarayonini tashkil etuvchi vositalar majmui."},
      {n:15, w:'MALAKAOSHIRISH', r:9, c:17, d:'V', q:"Kasbiy bilimlarni boyitish jarayoni."},
      {n:14, w:'OZINIRIVOJLANTIRISH', r:0, c:12, d:'V', q:"O'z ustida ishlash jarayoni."},
      {n:12, w:'RIVOJLANISH', r:1, c:10, d:'V', q:"Taraqqiyot va o'sish jarayoni."},
      {n:10, w:'TAFAKKUR', r:19, c:10, d:'H', q:"Yangicha fikr yuritish qobiliyati."},
      {n:9, w:'KOMPETENSIYA', r:9, c:15, d:'H', q:"Bilimlarni amalda qo'llash qobiliyati."},
      {n:8, w:'MAHORAT', r:22, c:15, d:'H', q:"Pedagogning kasbiy rivojlanish darajasi."},
      {n:7, w:'TADQIQOT', r:20, c:13, d:'H', q:"Ilmiy izlanish olib borish faoliyati."},
      {n:5, w:'MODELLASHTIRISH', r:2, c:0, d:'H', q:"Model yaratish jarayoni."},
      {n:4, w:'INNOVATSIYA', r:18, c:17, d:'H', q:"Yangilik yaratish va joriy etish jarayoni."},
      {n:3, w:'TEXNOPARK', r:0, c:8, d:'H', q:"Innovatsion faoliyat markazi."},
      {n:2, w:'STARTAP', r:21, c:17, d:'H', q:"Innovatsion biznes g'oyasi asosidagi loyiha."},
      {n:13, w:'IJODKORLIK', r:18, c:25, d:'V', q:"Yangi g'oyalarni yaratish faoliyati."},
      {n:11, w:'METODIKA', r:13, c:14, d:'V', q:"Ta'lim berish usullari tizimi."},
      {n:6, w:'KREATIVLIK', r:22, c:25, d:'H', q:"Yangi usullarni qo'llashga intilish."}
    ]},

  { id:13, title:"Pedagogik muloqot – o'qituvchining ijodiy faoliyati sifatida", sub:"Ijodkor fikrla – yangi yechim yarat!",
    words:[
      {n:1, w:'MULOQOT', r:4, c:13, d:'H', q:"O'zaro fikr almashish jarayoni."},
      {n:20, w:'RUHIYIQLIM', r:3, c:14, d:'V', q:"O'quvchi bilan psixologik yaqinlik holati."},
      {n:19, w:'MADANIYAT', r:4, c:13, d:'V', q:"Muloqot samaradorligini belgilovchi omil."},
      {n:18, w:'MODELLASHTIRISH', r:3, c:16, d:'V', q:"Muloqotni rejalashtirish bosqichi."},
      {n:17, w:'TINGLASH', r:4, c:19, d:'V', q:"O'quvchining fikrini eshitish jarayoni."},
      {n:16, w:'HAMKORLIK', r:0, c:18, d:'V', q:"Pedagogik muloqotning asosiy maqsadi."},
      {n:15, w:'NUTQ', r:1, c:17, d:'V', q:"Axborot almashish vositasi."},
      {n:12, w:'LIBERAL', r:4, c:15, d:'V', q:"Erkinlikka asoslangan boshqaruv usuli."},
      {n:10, w:'ALOQA', r:9, c:19, d:'H', q:"Axborot uzatish jarayoni."},
      {n:9, w:'MOTIVATSIYA', r:13, c:13, d:'H', q:"O'quvchini faollashtirish vositasi."},
      {n:8, w:'ISHONCH', r:15, c:16, d:'H', q:"Suhbat davomida ishonch hosil qilish holati."},
      {n:7, w:'KOMMUNIKATSIYA', r:16, c:6, d:'H', q:"Muloqot orqali ta'sir ko'rsatish jarayoni."},
      {n:5, w:'DEMOKRATIK', r:14, c:11, d:'H', q:"Tenglikka asoslangan boshqaruv usuli."},
      {n:14, w:'TAVOZE', r:6, c:21, d:'V', q:"Muloqot odobining muhim elementi."},
      {n:13, w:'PEDAGOGIKTASIR', r:8, c:6, d:'V', q:"O'quvchilarga ta'sir ko'rsatish qobiliyati."},
      {n:11, w:'AVTORITAR', r:2, c:23, d:'V', q:"Qattiq nazoratga asoslangan boshqaruv usuli."},
      {n:6, w:'MUNOSABAT', r:13, c:3, d:'H', q:"O'qituvchi va o'quvchi o'rtasidagi aloqa."},
      {n:4, w:'PERSEPTIV', r:21, c:4, d:'H', q:"Suhbatdoshni tushunishga qaratilgan muloqot turi."},
      {n:3, w:'INTERAKTIV', r:20, c:6, d:'H', q:"O'zaro ta'sirga asoslangan muloqot turi."},
      {n:2, w:'KOMMUNIKATIV', r:15, c:0, d:'H', q:"Aloqa o'rnatishga oid tushuncha."}
    ]},

  { id:14, title:"Bo'lajak o'qituvchilar ijodkorligini rivojlantirishda pedagogik texnologiyalarning o'rni", sub:"Ijodkor fikrla – yangi yechim yarat!",
    words:[
      {n:1, w:'INERSIYA', r:7, c:9, d:'H', q:"Eski qarashlarga bog'lanib qolish holati."},
      {n:20, w:'KREATIVLIK', r:6, c:12, d:'V', q:"Zamonaviy ta'limning muhim talabi."},
      {n:19, w:'NATIJA', r:7, c:10, d:'V', q:"Pedagogik faoliyat samaradorligi ko'rsatkichi."},
      {n:18, w:'MOTIVATSIYA', r:4, c:9, d:'V', q:"O'quvchining ijodiy salohiyatini rivojlantiruvchi omil."},
      {n:17, w:'TADQIQOT', r:6, c:16, d:'V', q:"Talabalarni izlanishga undovchi faoliyat."},
      {n:16, w:'KLASTERLASH', r:4, c:13, d:'V', q:"Fikrlarni guruhlash usuli."},
      {n:15, w:'MUSTAQIL', r:1, c:14, d:'V', q:"O'z kuchi bilan bajariladigan faoliyat."},
      {n:13, w:'BALIQSKELETI', r:0, c:11, d:'V', q:"Sabab va oqibatlarni aniqlash usuli."},
      {n:10, w:'INNOVATSIYA', r:13, c:0, d:'H', q:"Ta'lim jarayonidagi yangilik."},
      {n:9, w:'KOMPETENSIYA', r:15, c:12, d:'H', q:"O'quv faoliyatining natijasi."},
      {n:8, w:'BRAINSTORMING', r:0, c:11, d:'H', q:"Yangi g'oyalarni ishlab chiqish usuli."},
      {n:7, w:'INTERAKTIVLIK', r:10, c:16, d:'H', q:"O'quvchilarni faol ishtirokga jalb etuvchi usul."},
      {n:6, w:'MUAMMOLIOQITISH', r:3, c:1, d:'H', q:"Muammolarni hal qilishga qaratilgan ta'lim turi."},
      {n:5, w:'LOYIHA', r:14, c:4, d:'H', q:"Maqsadli amaliy faoliyat."},
      {n:2, w:'TEXNOLOGIYA', r:6, c:16, d:'H', q:"Faoliyatni tashkil etish usullari tizimi."},
      {n:14, w:'INNOVATSION', r:6, c:7, d:'V', q:"Yangilikka asoslangan faoliyat."},
      {n:12, w:'MUAMMOLI', r:8, c:21, d:'V', q:"Muammo yechishga asoslangan ta'lim."},
      {n:11, w:'INTERAKTIV', r:5, c:0, d:'V', q:"Faol muloqotga asoslangan ta'lim turi."},
      {n:4, w:'KLASTER', r:14, c:20, d:'H', q:"Fikrlarni tarmoqlash usuli."},
      {n:3, w:'IJODKORLIK', r:13, c:19, d:'H', q:"Yangi g'oyalar yaratish qobiliyati."}
    ]}

];
